### ISSUE TITLE
Build Errors using Unity 4.3.4f1

### ISSUE THREAD

**Issue by Bungalow12** [bitrave/azure-mobile-services-for-unity3d#10]
I may be using the wrong version of Unity perhaps but when I attempt to debug using MonoDevelop I see 6 errors like the following:

Unity\Assets\Scripts\AzureMobileServices\AzureMobileServices.cs(73,73): Error CS0241: Default parameter specifiers are not permitted (CS0241) (Assembly-CSharp)

**Comment by rtargosz** [comment]
You need to change the project .NET version to 4.0.

**Comment by Bungalow12** [comment]
Thanks!

**Comment by eivholt** [comment]
I use a plugin that automatically changes the mono project to reference .net 4.0 so I don´t have to do this all the time. Found it on the unity3d forum somewhere.

**Comment by eivholt** [comment]
http://forum.unity3d.com/threads/145027-Unity-is-overwriting-my-MonoDevelop-target-framework-setting-every-time-it-syncs?p=1449879&viewfull=1#post1449879

**Comment by Bungalow12** [comment]
I found it easier since this code is not changing frequently to clean up my project by building a DLL and referencing that. All it takes is some small additions to the csproj file and you have the pdb converted to an mdb for easy debugging.
