### ISSUE TITLE
Getting Authentication Token sample

### ISSUE THREAD

**Issue by Bungalow12** [bitrave/azure-mobile-services-for-unity3d#14]
Hi all,
I have never before created any applications using authentication from other services such as Microsoft account, facebook, google, or twitter. I have each registered with their app id and app secret for each service. My question is how do you get the users authentication token for these services prior to the AzureMobileServices.LoginAsync call which requires a string token?
Do I need to find separate APIs for each for Unity and use those or is there some other way? Also canmultiple accounts be associated with a single MobileServicesUser?

**Comment by vaughanknight** [comment]
Yep, you need to use a separate api for the authentication platform you
need.  AMS has some built in authentication flows, but you'll find that you
won't want to use these, and considering it's 4 lines of code for most of
the other API's, not needed.

Grab the token for example, from the facebook api, and then authenticate
using that with azure mobile services.

VK

**Comment by Bungalow12** [comment]
Excellent I will do that. Do you have any suggestions for different authentication platforms for unity?

**Comment by vaughanknight** [comment]
Usually native plugins, although I think Facebook has their own SDK for
Unity these days.  Also, check out the Unity asset store, most of the
solutions will be there already.

**Comment by Bungalow12** [comment]
Thanks!
