### ISSUE TITLE
Status "200 OK" but received Data = null

### ISSUE THREAD

**Issue by FlashMuller** [bitrave/azure-mobile-services-for-unity3d#28]
Hey guys,
I am trying to set up the most simple way of a user querying data from an azure sql. No LogIn, no inserting / editing, just check if a value exists. I have taken the tutorial from deadlyfingers (leaderboard) to get started. It seems to be working to a certain extent. When using azure.Where<>() the callback says the status is 200 OK (which is fine, as far as I can see), but it never has any data. What might be the reason for that? I'm completely new to Azure / bitrave-Plug-In and have no idea where to start searching.
I believe that there might be two issues: 
1 being access rights to the database. In the tutorial from deadly fingers there is this image (http://www.deadlyfingers.net/wp-content/uploads/2014/11/Unity3D-BitRave-Azure-Leaderboard_06a.png) showing options to allow users to acces the database with only the appID as authentification. I couldn't find this option in azure anymore / anywhere. Might this be the reason? Where can I set this up?
2 the item I'm using might be the issue. Here is a screenshot from my database: 
![db](https://cloud.githubusercontent.com/assets/13029603/8325022/374b478e-1a56-11e5-87bf-27c0fe14be67.JPG)
And here is my DB-Item in C#:
![db_item](https://cloud.githubusercontent.com/assets/13029603/8325113/21c05c1e-1a57-11e5-8ff2-389ff393b9a6.PNG)
Is that as it should be?
Any help and ideas would be greatly appreciated.
Cheers,
Daniel

**Comment by MeltdownInteractive** [comment]
Daniel,

In all honesty, I bashed my head against the wall for many months trying to integrate Azure, it is a long and painful process, aside from all the tricks and hurdles and issues you need to google for. Do yourself a favour and use something like Gamesparks as your backend API, it really is a hell of a lot easier to work with.

Use it, don't use it. But that's advice from someone who has integrated a game with Azure Mobile Services, and a game with GameSparks (in a fraction of the time), and I'm a very experienced developer (15 years).

**Comment by FlashMuller** [comment]
Yeah, anyone reading this: MetldownZA is right. I started trying out GameSparks 2 days ago - as I was stuck with the azure issue postet above, so why not give it a try. I had my (quite simple) system integrated by yesterday. This is nothing about this plug in. It's just such a bad documentation for azure (100% of the tutorials were outdated) and so hard to guess what you could / should / have to do.
Thanks for your opinion!
