### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by eivholt** [bitrave/azure-mobile-services-for-unity3d#3]
Hi, I think this is a really useful effort. What is the current status of the project? What are the main issues in supporting iOS and Android?

**Comment by vaughanknight** [comment]
We're uploading a version that supports everything today.  And by everything, we mean, every Unity target.  It makes the old plugin obsolete, and has authentication support etc.  We've done a lot of testing, but all feedback welcome as with supporting every platform, there is surely going to be edge cases.  It also breaks the old version, in short, it's a whole new version that is similar, but runs on XBox, Playstation, PS Vita etc etc... everything Unity runs on, including async in the editor.

**Comment by eivholt** [comment]
Great work, will start working with this asap!

**Comment by vaughanknight** [comment]
Let me know if you have issues... it works for all the bits we do, but since we rebuilt the entire Azure Mobile Services client from the ground up... anything could behave strange that we haven't picked up.
