### ISSUE TITLE
Is the universal plugin supposed to work for windows phone?

### ISSUE THREAD

**Issue by adampound** [bitrave/azure-mobile-services-for-unity3d#30]
im getting restsharp errors.

**Comment by adampound** [comment]
if been at this for 2 days. I   If I use the universal project I get this message when trying to build

Error: type `System.Net.CredentialCache` doesn't exist in target framework. It is referenced from RestSharp.dll at System.Void RestSharp.NtlmAuthenticator
Ive tried several different versions of restsharp.

if I used bitrave,azure.dll in the windows phone test project it builds but then I get 
An exception of type 'System.NotImplementedException' occurred in Bitrave.Azure.DLL but was not handled in user code

I also set all capabilities to on

**Comment by Frozenfire92** [comment]
@adampound Did you fix this?
